import streamlit as st
from dotenv import load_dotenv
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
import google.generativeai as genai
import os
import requests
import tempfile
from fpdf import FPDF
import unicodedata

# Load environment variables
load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# App Config
st.set_page_config(page_title="YouTube Summarizer", layout="centered")
st.markdown("""
    <style>
        @media only screen and (max-width: 768px) {
            h2 { font-size: 1.5em !important; }
            .stButton>button { width: 100% !important; }
        }
    </style>
""", unsafe_allow_html=True)
st.markdown("<h2 style='text-align:center; color:#4CAF50;'>🎥 YouTube Video Summarizer</h2>", unsafe_allow_html=True)

# Extract Video ID
def get_video_id(url):
    try:
        return url.split("v=")[1].split("&")[0]
    except:
        return None

# Fetch Transcript (English only)
def get_transcript(video_id):
    try:
        return YouTubeTranscriptApi.get_transcript(video_id, languages=["en"])
    except TranscriptsDisabled:
        st.error("❌ Transcripts are disabled for this video.")
    except Exception as e:
        st.error(f"❌ Transcript error: {e}")
    return None

# Extract transcript text
def extract_text(transcript_data):
    return " ".join(t["text"] for t in transcript_data) if transcript_data else None

# Prepare Gemini prompt
def make_prompt(text):
    return f"You are a helpful assistant that summarizes YouTube videos. Summarize the transcript below into key points in under 900 words:\n\n{text}"

# Choose Gemini model
def find_suitable_gemini_model():
    preferred = ["gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
    try:
        models = [m.name for m in genai.list_models() if "generateContent" in m.supported_generation_methods]
        for p in preferred:
            for m in models:
                if p in m:
                    return m
        return models[0] if models else None
    except Exception as e:
        st.error(f"Model lookup failed: {e}")
        return None

# Summarize transcript
def generate_summary(text):
    model_name = find_suitable_gemini_model()
    if not model_name:
        return None
    model = genai.GenerativeModel(model_name)
    try:
        return model.generate_content(make_prompt(text)).text
    except Exception as e:
        st.error(f"Failed to summarize: {e}")
        return None

# Clean text for PDF
def clean_text(text):
    replacements = {"“": '"', "”": '"', "‘": "'", "’": "'", "–": "-", "—": "-", "…": "...", "•": "-", "→": "->", "←": "<-"}
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = unicodedata.normalize("NFKD", text)
    return text.encode("latin-1", "replace").decode("latin-1")

# PDF class
class StyledPDF(FPDF):
    def header(self):
        if os.path.exists("logo.png"):
            self.image("logo.png", 10, 8, 15)
        self.set_font("Helvetica", 'B', 16)
        self.set_text_color(0, 102, 204)
        self.cell(0, 10, "NoteTube - YouTube Summary", ln=True, align="C")
        self.ln(8)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by NoteTube", 0, 0, "C")

    def add_summary(self, text):
        self.set_font("Times", size=12)
        self.set_text_color(33, 33, 33)
        self.set_left_margin(20); self.set_right_margin(20)
        for line in text.replace("*", "").split("\n"):
            clean_line = clean_text(line.strip())
            if clean_line:
                self.multi_cell(0, 8, clean_line)
                self.ln(2)

# Generate PDF file
def generate_styled_pdf(text):
    pdf = StyledPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.add_summary(text)
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        return tmp.name

# Fetch video metadata
def fetch_video_info(video_id):
    res = requests.get(
        "https://www.googleapis.com/youtube/v3/videos",
        params={"part":"snippet,statistics", "id":video_id, "key":os.getenv("YOUTUBE_API_KEY")}
    ).json()
    try:
        i = res["items"][0]
        return i["snippet"]["title"], i["snippet"]["channelTitle"], i["statistics"]["viewCount"], i["snippet"]["publishedAt"]
    except:
        return None, None, None, None

# UI Input & Logic
youtube_link = st.text_input("🔗 Enter YouTube Link", placeholder="https://www.youtube.com/watch?v=VIDEO_ID")
video_id = get_video_id(youtube_link) if youtube_link else None

if video_id:
    st.image(f"http://img.youtube.com/vi/{video_id}/0.jpg", use_container_width=True)
    title, channel, views, date = fetch_video_info(video_id)
    if title:
        st.markdown(f"**🎬 {title}**")
        st.markdown(f"**📺 {channel} • {int(views):,} views • {date[:10]}**")

if st.button("📝 Generate Notes"):
    if not video_id:
        st.error("Invalid YouTube link.")
    else:
        with st.spinner("🔄 Summarizing..."):
            data = get_transcript(video_id)
            text = extract_text(data)
            if text:
                summary = generate_summary(text)
                if summary:
                    st.session_state["summary"] = summary
                    st.success("✅ Summary Generated!")
                    st.markdown("### 📄 Summary Output")
                    st.write(summary)
                else:
                    st.error("⚠️ Summary failed to generate.")
            else:
                st.error("❌ Transcript not available or blocked by YouTube.")

if "summary" in st.session_state:
    st.markdown("---")
    st.markdown("### 📥 Download Summary as PDF")
    pdf_path = generate_styled_pdf(st.session_state["summary"])
    with open(pdf_path, "rb") as f:
        st.download_button("📄 Download PDF", f, file_name=f"summary_{video_id}.pdf", mime="application/pdf")

# Footer
st.markdown("""
<hr><div style='text-align:center; color:gray; font-size:0.9em;'>
Made with ❤️ by <b>Anindya Maity</b> | Powered by <i>Google Gemini & Streamlit</i>
</div>
""", unsafe_allow_html=True)
