import streamlit as st
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
import google.generativeai as genai
import requests
import tempfile
from fpdf import FPDF
import unicodedata
import os

# Configure Gemini with Streamlit secrets
genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])

# Theme toggle
theme = st.sidebar.radio("🌗 Theme", ["Light", "Dark"])
if theme == "Dark":
    st.markdown("""
        <style>
        body { background-color: #0e1117; color: white; }
        .stButton>button, .stTextInput>div>div>input, .stDownloadButton>button {
            background-color: #1f222a; color: white;
        }
        </style>
    """, unsafe_allow_html=True)

# App config
st.set_page_config(page_title="YouTube Summarizer", layout="centered")
st.markdown("<h2 style='text-align:center; color:#4CAF50;'>🎥 YouTube Video Summarizer</h2>", unsafe_allow_html=True)

# Extract video ID
def get_video_id(url):
    try:
        if "youtu.be/" in url:
            return url.split("youtu.be/")[1].split("?")[0]
        return url.split("v=")[1].split("&")[0]
    except:
        return None

# Get English transcript only
def get_transcript(video_id):
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
        transcript = transcript_list.find_transcript(["en"])
        return transcript.fetch()
    except:
        return None

def extract_text(transcript_data):
    return " ".join([entry["text"] for entry in transcript_data]) if transcript_data else None

def make_prompt(text):
    return f"You are a helpful assistant that summarizes YouTube videos. Summarize in key points under 900 words:\n\n{text}"

def find_suitable_gemini_model():
    preferred = ["gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
    try:
        models = [m.name for m in genai.list_models() if "generateContent" in m.supported_generation_methods]
        for p in preferred:
            for m in models:
                if p in m:
                    return m
        return models[0] if models else None
    except Exception as e:
        st.error(f"Model lookup failed: {e}")
        return None

def generate_summary(text):
    model = genai.GenerativeModel(find_suitable_gemini_model())
    try:
        return model.generate_content(make_prompt(text)).text
    except Exception as e:
        st.error(f"Failed to summarize: {e}")
        return None

def clean_text(text):
    repl = {
        "“": '"', "”": '"', "‘": "'", "’": "'",
        "–": "-", "—": "-", "…": "...",
        "•": "-", "→": "->", "←": "<-"
    }
    for old, new in repl.items():
        text = text.replace(old, new)
    text = unicodedata.normalize("NFKD", text)
    return text.encode("latin-1", "replace").decode("latin-1")

class StyledPDF(FPDF):
    def header(self):
        if os.path.exists("logo.png"):
            self.image("logo.png", 10, 8, 15)
        self.set_font("Helvetica", 'B', 16)
        self.set_text_color(0, 102, 204)
        self.cell(0, 10, "NoteTube - YouTube Summary", ln=True, align="C")
        self.ln(8)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by NoteTube", 0, 0, "C")

    def add_summary(self, summary_text):
        self.set_font("Times", size=12)
        self.set_text_color(33, 33, 33)
        self.set_left_margin(20)
        self.set_right_margin(20)
        for line in summary_text.replace("*", "").split("\n"):
            clean_line = clean_text(line.strip())
            if clean_line:
                self.multi_cell(0, 8, clean_line)
                self.ln(2)

def generate_styled_pdf(summary_text):
    pdf = StyledPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.add_summary(summary_text)
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        return tmp.name

# Fetch metadata
def fetch_video_info(video_id):
    API_KEY = st.secrets["YOUTUBE_API_KEY"]
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={video_id}&key={API_KEY}"
    try:
        res = requests.get(url).json()
        item = res["items"][0]
        snippet = item["snippet"]
        stats = item["statistics"]
        return snippet["title"], snippet["channelTitle"], stats["viewCount"], snippet["publishedAt"]
    except:
        return None, None, None, None

# UI
youtube_link = st.text_input("🔗 Enter YouTube Link", placeholder="https://youtu.be/VIDEO_ID")
video_id = get_video_id(youtube_link) if youtube_link else None

if video_id:
    st.image(f"http://img.youtube.com/vi/{video_id}/0.jpg", use_container_width=True)
    title, channel, views, date = fetch_video_info(video_id)
    if title:
        st.markdown(f"**🎬 {title}**")
        st.markdown(f"**📺 {channel} • {int(views):,} views • {date[:10]}**")

if st.button("📝 Generate Notes"):
    if not video_id:
        st.error("Invalid YouTube link.")
    else:
        with st.spinner("🔄 Summarizing..."):
            transcript_data = get_transcript(video_id)
            transcript_text = extract_text(transcript_data)
            if transcript_text:
                summary = generate_summary(transcript_text)
                if summary:
                    st.session_state["summary_text"] = summary
                    st.success("✅ Summary Generated!")
                    st.markdown("### 📄 Summary Output")
                    st.write(summary)
                else:
                    st.error("⚠️ Failed to generate summary.")
            else:
                st.error("❌ Transcript not available or must be in English.")

# PDF + Feedback
if "summary_text" in st.session_state:
    st.markdown("---")
    st.markdown("### ⭐ Rate the Output")
    rating = st.feedback("stars", key="rating_feedback")
    if rating is not None:
        st.info(f"You rated: {rating + 1}/5")

    st.markdown("### 📥 Download Summary as PDF")
    pdf_path = generate_styled_pdf(st.session_state["summary_text"])
    with open(pdf_path, "rb") as pdf_file:
        st.download_button(
            label="📄 Download PDF",
            data=pdf_file,
            file_name=f"summary_{video_id}.pdf",
            mime="application/pdf"
        )

# Footer
st.markdown("""
<hr>
<div style='text-align: center; color: gray; font-size: 0.9em;'>
    Made with ❤️ by <b>Anindya Maity</b> | Powered by <i>Google Gemini & Streamlit</i>
</div>
""", unsafe_allow_html=True)
